server:
  port: 8080

logging:
  level:
    root: info

dubbo:
  application:
    name: gmall-mumber-web-consumer
  registry:
    address: zookeeper://120.76.139.86:2181
  monitor:
    protocol: registry